name: Add member
description: Add a lab member
title: "[Add member]: "
labels: ["automatic-add-member"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form!

  - type: input
    id: name
    attributes:
      label: Name
      description: Full name of the new member
      placeholder: "John Doe"
    validations:
      required: true

  - type: dropdown
    id: role
    attributes:
      label: "Role"
      description: What's the role of the new member?
      multiple: false
      options:
        - "Faculty"
        - "Postdoc"
        - "PhD"
        - "Master"
        - "Undergraduate"
        - "Intern"
    validations:
      required: true

  - type: "input"
    id: avatar
    attributes:
      label: "Avatar"
      description: "Link to the avatar of the new member"
      placeholder: "https://example.com/avatar.png"
    validations:
      required: false

  - type: "input"
    id: advisor
    attributes:
      label: "Advisor(s) (for students)"
      description: "Who is/are the advisor(s) of the new member if they are a student?"
      placeholder: "John Doe Jr."
    validations:
      required: false

  - type: "input"
    id: date
    attributes:
      label: "Date"
      description: "When did the new member join the lab? MMM-YYYY or {Fall, Winter} YYYY"
      placeholder: "Jan 2021"
    validations:
      required: false

  - type: "textarea"
    id: bio
    attributes:
      label: "Bio"
      description: "What's the bio of the new member?"
      placeholder: "Just a cool student!"

  - type: "input"
    id: note
    attributes:
      label: "Note"
      description: "Any special note"
      placeholder: "h-index: 9001"

  - type: "input"
    id: github
    attributes:
      label: "GitHub"
      description: "Full URL of the new member's GitHub profile"
      placeholder: "https://github.com/john-doe"
    validations:
      required: false
  
  - type: "input"
    id: twitter
    attributes:
      label: "Twitter"
      description: "Full URL of the new member's Twitter profile"
      placeholder: "https://twitter.com/john-doe"
    validations:
      required: false
    
  - type: "input"
    id: scholar
    attributes:
      label: "Scholar"
      description: "Full URL of the new member's Google Scholar profile"
      placeholder: "https://scholar.google.com/citations?user=<user_id>"
    validations:
      required: false

  - type: "input"
    id: website
    attributes:
      label: "Website"
      description: "Full URL of the new member's website"
      placeholder: "https://john-doe.github.io/"
    validations:
      required: false

  - type: dropdown
    id: alumni
    attributes:
      label: "Current Status"
      description: |
        What's the current status of the new member?
      multiple: false
      options:
        - "Alumni"
        - "Current Member"
    validations:
      required: true

  - type: "input"
    id: new_role
    attributes:
      label: "New role (if alumni)"
      description: "Only if the new member is an alumni, what's the new role?"
      placeholder: "Professing at Leland Junior S. University"
    validations:
      required: false
