name: "Parse and process issues"
on:
  issues:
    types: [opened, reopened]

jobs:
  parse-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check issue title
        env:
          TITLE: "${{ github.event.issue.title }}"
        run: echo "$TITLE"
