name: "Parse and process issue form"
on:
  issues:
    types: [opened, reopened]


jobs:
  show-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Show label
        env:
          LABEL: "${{ github.event.label }}"
          ISSUES: "${{ github.event.issues }}"
        run: |
          echo "LABEL: $LABEL"
          echo "ISSUES: $ISSUES"
    
  parse-issue:
    if: contains(github.event.issues.labels.*.name, 'automatic')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python: "3.8"
      - name: Foo
        env:
          BODY: ${{ github.event.issue.body }}
        run: |
          import os
          body = os.environ['BODY']
          print("Foo bar")
          print(body)
        shell: python