name: "Parse and process issue forms"
on:
  issues:
    types:
      - labeled

jobs:
  process-issue-forms:
    if: startsWith(github.event.label.name, 'automatic-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Python requirements
        run: pip install -r src/python/requirements.txt

      - name: "Update _data/authors.yml with src/python/add_author.py"
        if: github.event.label.name == 'automatic-add-member'
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: python src/python/add_author.py
      
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          delete-branch: true
          branch-suffix: timestamp
          commit-message: "[GH Actions] Add new member"
          title: "[Automatic PR] ${{ github.event.issue.title }}"
          body: "Closes issue #${{ github.event.issue.number }}. This pull request was automatically created through GitHub Actions."
          branch: "gh-actions/process-form-issue-${{ github.event.issue.number }}"